export const routes = {
	root: "/",
	login: "/auth/login",
	changePassword: "/auth/change-password",
	status: "/status",
	notAuthorized: "/not-authorized",
	appRoot: "/app",
	workspace: "/app/workspace",
	workspaceLoans: "/app/workspace/loans",
	workspaceLoanWizardNew: "/app/workspace/loans/new",
	workspaceLoanWizardEdit: "/app/workspace/loans/:id/edit",
	workspaceLoanDetail: "/app/workspace/loans/:id",
	workspaceDocuments: "/app/workspace/documents",
	workspaceLoanDocuments: "/app/workspace/documents/:id",
	workspaceAmortization: "/app/workspace/amortization",
	workspaceSettings: "/app/workspace/settings",
	workflows: "/app/workflows",
	workflowsQueue: "/app/workflows/queue",
	workflowsRequestDetail: "/app/workflows/requests/:requestId",
	loans: "/app/loans",
	loansDetail: "/app/loans/:loanId",
	stockOverview: "/app/stock",
	stockManage: "/app/stock/manage",
	stockGrants: "/app/stock/grants",
	stockVesting: "/app/stock/vesting",
	peopleUsers: "/app/people/users",
	peopleUserDetail: "/app/people/users/:membershipId",
	peopleUsersOnboard: "/app/people/users/onboard",
	peopleRoles: "/app/people/roles",
	peopleDepartments: "/app/people/departments",
	documents: "/app/documents",
	documentsTemplates: "/app/documents/templates",
	documentsPackets: "/app/documents/packets",
	announcements: "/app/announcements",
	settingsOrg: "/app/settings/org",
	settingsAudit: "/app/settings/audit",
	adminTenancy: "/app/admin/tenancy",
	adminFeatureFlags: "/app/admin/feature-flags",
	auth: {
		root: "/auth",
		login: () => "/auth/login",
		changePassword: () => "/auth/change-password",
	},
} as const;

export type { AppRoute } from "@/shared/lib/types";
