export const routes = {
	root: "/",
	login: "/auth/login",
	changePassword: "/auth/change-password",
	status: "/status",
	notAuthorized: "/not-authorized",
	appRoot: "/app",
	workspace: "/app/workspace",
	workspaceSettings: "/app/workspace/settings",
	workflows: "/app/workflows",
	loans: "/app/loans",
	stockOverview: "/app/stock",
	stockManage: "/app/stock/manage",
	stockGrants: "/app/stock/grants",
	stockVesting: "/app/stock/vesting",
	peopleUsers: "/app/people/users",
	peopleUserDetail: "/app/people/users/:membershipId",
	peopleUsersOnboard: "/app/people/users/onboard",
	peopleRoles: "/app/people/roles",
	peopleDepartments: "/app/people/departments",
	documents: "/app/documents",
	documentsTemplates: "/app/documents/templates",
	documentsPackets: "/app/documents/packets",
	announcements: "/app/announcements",
	settingsOrg: "/app/settings/org",
	settingsAudit: "/app/settings/audit",
	adminTenancy: "/app/admin/tenancy",
	adminFeatureFlags: "/app/admin/feature-flags",
	auth: {
		root: "/auth",
		login: () => "/auth/login",
		changePassword: () => "/auth/change-password",
	},
} as const;

type AppRouteKey = Exclude<keyof typeof routes, "auth">;
export type AppRoute = (typeof routes)[AppRouteKey];
