import { Badge } from "@/components/ui/badge";
import { PageHeader } from "@/components/common/PageHeader";
import { PageContainer } from "@/components/layout/PageContainer";
import { DataTable } from "@/components/data-table/DataTable";
import type { ColumnDefinition } from "@/components/data-table/types";
import type { BadgeVariant } from "@/components/ui/badge";
import type { DemoEmploymentType, DemoStatus, DemoTableRow } from "./types";

const currencyFormatter = new Intl.NumberFormat("en-US", {
	style: "currency",
	currency: "USD",
	maximumFractionDigits: 0,
});

const dateFormatter = new Intl.DateTimeFormat("en-US", {
	month: "short",
	day: "numeric",
	year: "numeric",
});

const dateTimeFormatter = new Intl.DateTimeFormat("en-US", {
	month: "short",
	day: "numeric",
	year: "numeric",
	hour: "numeric",
	minute: "2-digit",
});

const statusVariantMap: Record<DemoStatus, BadgeVariant> = {
	Active: "default",
	"On Leave": "secondary",
	Inactive: "outline",
};

const employmentOrder: Record<DemoEmploymentType, number> = {
	"Full-time": 1,
	"Part-time": 2,
	Contractor: 3,
};

const demoRows: DemoTableRow[] = [
	{
		id: "EMP-1001",
		employee: "Avery Jordan",
		department: "Finance",
		status: "Active",
		employmentType: "Full-time",
		startDate: "2021-03-12",
		lastActivity: "2025-12-20T14:22:00Z",
		loanBalance: 28000,
		riskScore: 72,
		manager: "Jordan Lee",
		notes: "",
	},
	{
		id: "EMP-1002",
		employee: "Maya Patel",
		department: "Engineering",
		status: "Active",
		employmentType: "Full-time",
		startDate: "2019-07-08",
		lastActivity: "2025-12-19T09:10:00Z",
		loanBalance: 54000,
		riskScore: 88,
		manager: "Xander Price",
		notes: "Promoted in Q4",
	},
	{
		id: "EMP-1003",
		employee: "Noah Kim",
		department: "Operations",
		status: "On Leave",
		employmentType: "Part-time",
		startDate: "2022-01-25",
		lastActivity: "2025-11-02T16:45:00Z",
		loanBalance: 12000,
		riskScore: 45,
		manager: null,
		notes: null,
	},
	{
		id: "EMP-1004",
		employee: "Lena Okafor",
		department: "People",
		status: "Active",
		employmentType: "Full-time",
		startDate: "2020-05-19",
		lastActivity: "2025-12-21T11:05:00Z",
		loanBalance: 19000,
		riskScore: 63,
		manager: "Harper Stone",
		notes: "Prefers email updates",
	},
	{
		id: "EMP-1005",
		employee: "Theo Ramirez",
		department: "Product",
		status: "Active",
		employmentType: "Contractor",
		startDate: "2023-09-04",
		lastActivity: "2025-12-18T19:30:00Z",
		loanBalance: 8000,
		riskScore: 38,
		manager: "Kara Wu",
		notes: "",
	},
	{
		id: "EMP-1006",
		employee: "Isla Nguyen",
		department: "Finance",
		status: "Inactive",
		employmentType: "Part-time",
		startDate: "2018-11-02",
		lastActivity: "2025-10-01T08:15:00Z",
		loanBalance: 32000,
		riskScore: 91,
		manager: "Jordan Lee",
		notes: "Exit scheduled",
	},
	{
		id: "EMP-1007",
		employee: "Eli Brooks",
		department: "Engineering",
		status: "Active",
		employmentType: "Contractor",
		startDate: "2024-02-14",
		lastActivity: "2025-12-20T13:02:00Z",
		loanBalance: 15000,
		riskScore: 52,
		manager: "Xander Price",
		notes: null,
	},
	{
		id: "EMP-1008",
		employee: "Priya Shah",
		department: "Legal",
		status: "Active",
		employmentType: "Full-time",
		startDate: "2017-06-30",
		lastActivity: "2025-12-17T12:40:00Z",
		loanBalance: 67000,
		riskScore: 76,
		manager: "Drew Bell",
		notes: "Review scheduled",
	},
	{
		id: "EMP-1009",
		employee: "Omar Haddad",
		department: "Operations",
		status: "On Leave",
		employmentType: "Full-time",
		startDate: "2016-09-12",
		lastActivity: "2025-11-28T17:00:00Z",
		loanBalance: 41000,
		riskScore: 67,
		manager: "Morgan Fields",
		notes: "",
	},
	{
		id: "EMP-1010",
		employee: "Vivian Chen",
		department: "Product",
		status: "Active",
		employmentType: "Full-time",
		startDate: "2020-01-06",
		lastActivity: "2025-12-22T10:20:00Z",
		loanBalance: 52000,
		riskScore: 81,
		manager: "Kara Wu",
		notes: "High priority",
	},
	{
		id: "EMP-1011",
		employee: "Caleb Ross",
		department: "Engineering",
		status: "Inactive",
		employmentType: "Contractor",
		startDate: "2022-10-03",
		lastActivity: "2025-09-14T09:45:00Z",
		loanBalance: 6000,
		riskScore: 34,
		manager: null,
		notes: "Return pending",
	},
	{
		id: "EMP-1012",
		employee: "Sofia Mendes",
		department: "People",
		status: "Active",
		employmentType: "Part-time",
		startDate: "2021-04-21",
		lastActivity: "2025-12-15T15:05:00Z",
		loanBalance: 23000,
		riskScore: 59,
		manager: "Harper Stone",
		notes: null,
	},
	{
		id: "EMP-1013",
		employee: "Julian Park",
		department: "Legal",
		status: "Active",
		employmentType: "Full-time",
		startDate: "2015-12-18",
		lastActivity: "2025-12-11T11:12:00Z",
		loanBalance: 74000,
		riskScore: 83,
		manager: "Drew Bell",
		notes: "",
	},
	{
		id: "EMP-1014",
		employee: "Nora Ali",
		department: "Operations",
		status: "Active",
		employmentType: "Full-time",
		startDate: "2020-08-10",
		lastActivity: "2025-12-20T08:00:00Z",
		loanBalance: 27000,
		riskScore: 62,
		manager: "Morgan Fields",
		notes: "Cross-training",
	},
	{
		id: "EMP-1015",
		employee: "Grace Kim",
		department: "Finance",
		status: "On Leave",
		employmentType: "Full-time",
		startDate: "2019-02-04",
		lastActivity: "2025-11-30T18:35:00Z",
		loanBalance: 36000,
		riskScore: 70,
		manager: "Jordan Lee",
		notes: null,
	},
	{
		id: "EMP-1016",
		employee: "Mateo Silva",
		department: "Product",
		status: "Active",
		employmentType: "Contractor",
		startDate: "2024-05-27",
		lastActivity: "2025-12-21T16:55:00Z",
		loanBalance: 9500,
		riskScore: 41,
		manager: "Kara Wu",
		notes: "",
	},
	{
		id: "EMP-1017",
		employee: "Zoe Bennett",
		department: "Engineering",
		status: "Active",
		employmentType: "Full-time",
		startDate: "2018-03-09",
		lastActivity: "2025-12-16T07:48:00Z",
		loanBalance: 61000,
		riskScore: 90,
		manager: "Xander Price",
		notes: "Top performer",
	},
	{
		id: "EMP-1018",
		employee: "Hassan Noor",
		department: "People",
		status: "Inactive",
		employmentType: "Part-time",
		startDate: "2016-01-11",
		lastActivity: "2025-08-19T13:20:00Z",
		loanBalance: 11000,
		riskScore: 48,
		manager: null,
		notes: "",
	},
	{
		id: "EMP-1019",
		employee: "Elena Petrova",
		department: "Legal",
		status: "Active",
		employmentType: "Contractor",
		startDate: "2023-03-20",
		lastActivity: "2025-12-12T10:05:00Z",
		loanBalance: 15000,
		riskScore: 57,
		manager: "Drew Bell",
		notes: "Pending review",
	},
	{
		id: "EMP-1020",
		employee: "Quinn Harper",
		department: "Operations",
		status: "Active",
		employmentType: "Full-time",
		startDate: "2021-10-15",
		lastActivity: "2025-12-20T20:10:00Z",
		loanBalance: 29000,
		riskScore: 65,
		manager: "Morgan Fields",
		notes: "",
	},
];

const demoColumns: ColumnDefinition<DemoTableRow>[] = [
	{
		id: "employee",
		header: "Employee",
		accessor: "employee",
	},
	{
		id: "department",
		header: "Department",
		accessor: "department",
	},
	{
		id: "status",
		header: "Status",
		accessor: "status",
		cell: (row) => (
			<Badge variant={statusVariantMap[row.status]}>{row.status}</Badge>
		),
	},
	{
		id: "employmentType",
		header: "Employment",
		accessor: "employmentType",
		sortAccessor: (row) => employmentOrder[row.employmentType],
	},
	{
		id: "loanBalance",
		header: "Loan balance",
		accessor: "loanBalance",
		cell: (row) => currencyFormatter.format(row.loanBalance),
		sortAccessor: (row) => row.loanBalance,
		filterAccessor: (row) => row.loanBalance,
		exportAccessor: (row) => row.loanBalance,
		headerClassName: "text-right",
		cellClassName: "text-right",
	},
	{
		id: "riskScore",
		header: "Risk score",
		accessor: "riskScore",
		sortAccessor: (row) => row.riskScore,
		filterAccessor: (row) => row.riskScore,
		headerClassName: "text-right",
		cellClassName: "text-right",
	},
	{
		id: "startDate",
		header: "Start date",
		accessor: "startDate",
		cell: (row) => dateFormatter.format(new Date(row.startDate)),
		sortAccessor: (row) => new Date(row.startDate),
		filterAccessor: (row) => row.startDate,
	},
	{
		id: "lastActivity",
		header: "Last activity",
		accessor: "lastActivity",
		cell: (row) => dateTimeFormatter.format(new Date(row.lastActivity)),
		sortAccessor: (row) => new Date(row.lastActivity),
		filterAccessor: (row) => row.lastActivity,
	},
	{
		id: "manager",
		header: "Manager",
		accessor: "manager",
		cell: (row) => row.manager ?? "—",
	},
	{
		id: "notes",
		header: "Notes",
		accessor: "notes",
		cell: (row) => row.notes?.trim() ? row.notes : "—",
		enableSorting: false,
	},
];

export function DataTableDemoPage() {
	return (
		<PageContainer>
			<PageHeader
				title="Data table demo"
				subtitle="Preview the new table behaviors: sorting, filtering, column visibility, selection, export, and pagination."
			/>
			<DataTable
				data={demoRows}
				columns={demoColumns}
				getRowId={(row) => row.id}
				preferences={{ id: "data-table-demo", scope: "global" }}
				pagination={{
					enabled: true,
					pageSize: 8,
					pageSizeOptions: [8, 16, 24],
				}}
			/>
		</PageContainer>
	);
}
